apiVersion: v1
kind: ServiceAccount
metadata:
  name: raven-controller-manager
  namespace: kube-system
  labels:
    diplomat: diplomat
    app: diplomat-raven-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: raven-leader-election-role
  namespace: kube-system
  labels:
    diplomat: diplomat
    app: diplomat-raven-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: raven-manager-role
  labels:
    diplomat: diplomat
    app: diplomat-raven-controller-manager
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - crd.projectcalico.org
    resources:
      - blockaffinities
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - raven.openyurt.io
    resources:
      - gateways
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - raven.openyurt.io
    resources:
      - gateways/finalizers
    verbs:
      - update
  - apiGroups:
      - raven.openyurt.io
    resources:
      - gateways/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: raven-metrics-reader
  labels:
    diplomat: diplomat
    app: diplomat-raven-controller-manager
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: raven-proxy-role
  labels:
    diplomat: diplomat
    app: diplomat-raven-controller-manager
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: raven-leader-election-rolebinding
  namespace: kube-system
  labels:
    diplomat: diplomat
    app: diplomat-raven-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: raven-leader-election-role
subjects:
  - kind: ServiceAccount
    name: raven-controller-manager
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: raven-manager-rolebinding
  labels:
    diplomat: diplomat
    app: diplomat-raven-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: raven-manager-role
subjects:
  - kind: ServiceAccount
    name: raven-controller-manager
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: raven-proxy-rolebinding
  labels:
    diplomat: diplomat
    app: diplomat-raven-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: raven-proxy-role
subjects:
  - kind: ServiceAccount
    name: raven-controller-manager
    namespace: kube-system
