apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: raven-agent-edge-ds
  namespace: diplomat
  labels:
    diplomat: diplomat
    app: diplomat-raven-agent
spec:
  selector:
    matchLabels:
      app: diplomat-raven-agent
      diplomat: diplomat
  template:
    metadata:
      labels:
        app: diplomat-raven-agent
        diplomat: diplomat
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: node-role.kubernetes.io/edge
                operator: Exists
              - key: node-role.kubernetes.io/agent
                operator: Exists
      containers:
      - env:
        - name: KUBERNETES_SERVICE_HOST
          value: 127.0.0.1
        - name: KUBERNETES_SERVICE_PORT
          value: "10550"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VPN_CONNECTION_PSK
          valueFrom:
            secretKeyRef:
              key: vpn-connection-psk
              name: raven-agent-secret
        - name: VPN_DRIVER
          valueFrom:
            configMapKeyRef:
              key: vpn-driver
              name: raven-agent-config
        # TODO
        image: a526102465/raven-agent:v0.0.1-diplomat
        imagePullPolicy: Always
        name: diplomat-raven-agent-edge
        securityContext:
          privileged: true
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: raven-agent-account
      tolerations:
      - operator: Exists
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5%
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: raven-agent-ds
  namespace: diplomat
  labels:
    diplomat: diplomat
    app: diplomat-raven-agent
spec:
  selector:
    matchLabels:
      app: diplomat-raven-agent
      diplomat: diplomat
  template:
    metadata:
      labels:
        app: diplomat-raven-agent
        diplomat: diplomat
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
              - key: node-role.kubernetes.io/agent
                operator: DoesNotExist
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VPN_CONNECTION_PSK
              valueFrom:
                secretKeyRef:
                  key: vpn-connection-psk
                  name: raven-agent-secret
            - name: VPN_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: vpn-driver
                  name: raven-agent-config
          # TODO
          image: a526102465/raven-agent:v0.0.1-diplomat
          imagePullPolicy: Always
          name: diplomat-raven-agent
          securityContext:
            privileged: true
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: raven-agent-account
      tolerations:
        - operator: Exists
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5%
