apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudcore
  namespace: kubeedge
  labels:
    app: diplomat-kubeedge
    kubeedge: cloudcore
    diplomat: diplomat
data:
  cloudcore.yaml: |
    apiVersion: cloudcore.config.kubeedge.io/v1alpha2
    kind: CloudCore
    kubeAPIConfig:
      kubeConfig: ""
      master: ""
    modules:
      cloudHub:
        advertiseAddress:
          - ""
        dnsNames:
          - ""
        nodeLimit: 1000
        tlsCAFile: /etc/kubeedge/tunnel/ca/rootCA.crt
        tlsCAKeyFile: /etc/kubeedge/tunnel/ca/rootCA.key
        tlsCertFile: /etc/kubeedge/tunnel/certs/edge.crt
        tlsPrivateKeyFile: /etc/kubeedge/tunnel/certs/edge.key
        unixsocket:
          address: unix:///var/lib/kubeedge/kubeedge.sock
          enable: true
        websocket:
          address: 0.0.0.0
          enable: true
          port: 10000
        quic:
          address: 0.0.0.0
          enable: false
          maxIncomingStreams: 10000
          port: 10001
        https:
          address: 0.0.0.0
          enable: true
          port: 10002
      cloudStream:
        enable: true
        streamPort: 10003
        tunnelPort: 10004
        tlsTunnelCAFile: /etc/kubeedge/tunnel/ca/rootCA.crt
        tlsTunnelCertFile: /etc/kubeedge/tunnel/certs/edge.crt
        tlsTunnelPrivateKeyFile: /etc/kubeedge/tunnel/certs/edge.key
        tlsStreamCAFile: /etc/kubeedge/stream/ca/streamCA.crt
        tlsStreamCertFile: /etc/kubeedge/stream/certs/stream.crt
        tlsStreamPrivateKeyFile: /etc/kubeedge/stream/certs/stream.key
      dynamicController:
        enable: true
      router:
        enable: false
      iptablesManager:
        enable: true
        mode: internal